### ISSUE TITLE
getTimezoneOffset second argument is required

### ISSUE THREAD

**Issue by Xhale1** [marnusw/date-fns-tz#283]
`getTimezoneOffset` seems to have a required second argument in version 3.1.1 when it wasn't previously required in 3.0.0.

**Comment by marnusw** [comment]
Fixed in `3.1.2`

**Comment by Xhale1** [comment]
Looks like the error still persists in `3.1.2`

<img width="489" alt="Screenshot 2024-04-16 at 2 04 27 PM" src="https://github.com/marnusw/date-fns-tz/assets/6383154/b649db5a-a3b4-4b36-a7e5-245108b4f9df">

**Comment by marnusw** [comment]
Try `v.3.1.3`. Sorry.

**Comment by Xhale1** [comment]
`3.1.3` works well, thank you!
