### ISSUE TITLE
Runtime error on IE 11

### ISSUE THREAD

**Issue by adrienharnay** [marnusw/date-fns-tz#6]
Hey,

It seems that there are `const` declarations in the es bundle, e.g.:

`date-fns-tz/esm/_lib/tzTokenizeDate/index.js`, l.23
```js
const { type, value } = formatted[i]
```

I only have 12 occurences of `const` in the whole output of my build, and I'm pretty sure it shouldn't occur, since IE doesn't support it.

Is there something I am missing here?

Thanks in advance!

**Comment by marnusw** [comment]
Odd. I thought I was using the same Babel configuration as `date-fns`. I will take a look.

**Comment by adrienharnay** [comment]
Hey, have you by any chance found the culprit?

**Comment by manojvignesh** [comment]
Did some debugging in this issue. I don't think there's any problem with the babel. It's transpiling correctly to the tmp/package folder when i run `yarn package`. But the compiled files are not copied to the source folder correctly. I think that's what package.js is trying to do.

**Comment by marnusw** [comment]
It turns out `date-fns` just doesn't use `const` in the source files and does not transpile the files when copying for the esm build. I have removed `const`, `let`, and other syntax which may be problematic. If I've missed anything just let me know.

**Comment by adrienharnay** [comment]
Everything seems perfect, thank you!

**Comment by adrienharnay** [comment]
Nope, spoke too soon, there is still detstructuring: `var{type:i,value:a}=n[o]`

**Comment by marnusw** [comment]
Fixed that, thanks.

**Comment by manojvignesh** [comment]
One more - [Array destructing](https://github.com/marnusw/date-fns-tz/blob/4ecc66661ea93effea469dafa497b8141dd22206/src/_lib/tzParseTimezone/index.js#L58).

**Comment by manojvignesh** [comment]
@marnusw Thanks you, It's working in IE. Verified.
@adrienharnay Babel is already there. Export statements are still present and are transpiled using babel.
But for some reason it was not done for the actual code. But yeah it'd be really good to have the babel setup to avoid these sort of issues.

**Comment by adrienharnay** [comment]
I will take a look this week-end :+1:

**Comment by marnusw** [comment]
Yeah, sorry about the round about on this guys. The only reason it is not there was because I wanted to keep the build process as close to the `date-fns` library as possible, because I hope this project might be integrated there eventually.

I don't really have any road map left for this project at the moment, so now that it's working there probably won't be further changes; but if you have time it probably couldn't hurt to have a transpilation step for the esm code as well.

Thanks again for the feedback and confirmations on this issue from you both.

**Comment by adrienharnay** [comment]
I opened an issue on `date-fns` (https://github.com/date-fns/date-fns/issues/1066). If they're interested in a PR I will do one on the main repo then one here :+1:

**Comment by marnusw** [comment]
I see, that sounds good. The eslint plugin will certainly help. Thanks @adrienharnay
